name: Pengaduan

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v3
    - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
    - name: Pengaduan
        uses: hafid/Pengaduan_Masyarakat-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: Pengaduan_Masyarakat
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
